version: '2.1'

services:
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - '8888:80'
      - '4433:443'
    volumes:
      - ./nginx.conf:/opt/bitnami/nginx/conf/nginx.conf
      - ./default.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf
        #- ./index.php:/var/www/html/index.php
    restart: unless-stopped
  phpfpm:
    image: 'bitnami/php-fpm:latest'
    networks:
      - app-tier
    volumes:
      - ./php-files:/var/www/html/
    restart: unless-stopped
  phpmyadmin:
    image: 'bitnami/phpmyadmin'
    networks:
      - app-tier
    ports:
      - '8081:8080'
      - '9090:8443'
    environment:
      - DATABASE_HOST=mysql
      #- PHPMYADMIN_ALLOW_ARBITRARY_SERVER=TRUE
    restart: unless-stopped
  mysql:
    env_file:
      - .env
    image: 'bitnami/mysql:latest'
    hostname: mariabd
    extra_hosts:
      - "mariadb:172.17.0.1"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      #- ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    volumes:
      - ./db:/bitnami/mysql/data
    restart: unless-stopped

networks:
  app-tier:
    driver: bridge
